### ISSUE TITLE
Mp3 take more then 10 seconds to start playing?

### ISSUE THREAD

**Issue by tejinderpaul** [teodorpatras/Jukebox#59]
I am working on a app where I have to play an mp3 player, in iOS I used jukebox library, thanks for providing such wonderful lib.

I am facing an issue which is if I play a mp3, it take aounrd more then 10-20 seconds to start song?Anu Idea?

**Comment by almatri** [comment]
The problem apparently is with iOS 10 devices only .
I fixed this by manually adding the library, and change each player.play() with this :

    if #available(iOS 10.0, *) {
        player?.playImmediately(atRate: 1.0)
    } else {
        player?.play()
    }

http://stackoverflow.com/questions/40442265/avplayer-takes-long-time-to-start-playing/42235181#42235181

I created PR here #64

**Comment by sandeepsipl** [comment]
I'm still facing this issue on iOS 11 with Swift 3. Any idea?

**Comment by tungdx** [comment]
In class Jukebox.swift, I added below code to method startNewPlayer(...) and it works
`if #available(iOS 10,*){
            player?.automaticallyWaitsToMinimizeStalling = false
        }`

**Comment by laraibmaliknew** [comment]
Any upadte on this?
